# Updated for REChain version 4.1.10+1160 - 2025-12-06
arb-dir: lib/l10n
template-arb-file: intl_en.arb
output-localization-file: l10n.dart
output-class: L10n
preferred-supported-locales: ["en"]
use-deferred-loading: true
nullable-getter: false
