display_name: REChain
icon: assets/logo.png
summary:  The inclusion of polls enhances decision-making processes by facilitating quick and efficient feedback gathering. Additionally, the platform supports user-friendly interface & goods!
group: Applications/Development Tools
vendor: REChain Network Solutions
packager: Sorokin Dmitry Olegovich
packagerEmail: dmitry.justdev@gmail.com
license: AGPL-3.0
url: https://github.com/sorydima/REChain-.git

#build_arch: aarch64

requires:
  - mpv
  - libjsoncpp-dev
  - libsecret-1-dev
  - libsecret-1-0
  - librhash0
  - libwebkit2gtk-4.0-dev
  - libolm3

keywords:
  - REChain
  - REChain Client

generic_name: REChain Client

categories:
  - Development
  - Utility

startup_notify: true
