
name: matrix-ultimate
base: core22
version: '4.1.10+1160'
summary: Matrix Ultimate Bundle - REChain v4.1.10+1160
description: |
  Full self-hosted Matrix server bundle with bridges and Element.
  REChain Matrix Bridge Setup Bundle v4.1.10+1160

confinement: strict

apps:
  matrix:
    command: docker-compose -f $SNAP/opt/matrix/docker-compose.yml up
    plugs: [network, network-bind]

parts:
  matrix:
    plugin: dump
    source: .
